/* Copyright 2020 QMK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was auto-generated by:
 *    `qmk chibios-confmigrate -i keyboards/acheron/arctic/mcuconf.h -r platforms/chibios/GENERIC_STM32_F072XB/configs/mcuconf.h`
 */

#pragma once

#include_next <mcuconf.h>
/*
//#undef SN32_PWM_USE_CT16B0

#define SN32_PWM_USE_CT16B0 TRUE
#define SN32_PWM_USE_CT16B1 TRUE
#define SN32_PWM_USE_CT16B2 TRUE
#define SN32_PWM_USE_CT16B5 TRUE

//#define SN32_SERIAL_USE_UART3 TRUE
#ifdef LK_WIRELESS_ENABLE
#define SN32_SPI_USE_SPI1 TRUE
#endif

#define SN32_SPI_USE_SPI1 TRUE
*/
